project:
  type: website
  output-dir: docs

website:
  title: "DS4I Assignment 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - allcode.qmd
      - writeup.qmd
      - appendix.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
